[package]
name = "random_data_generator"
version = "0.1.0"
authors = ["Tim <tim.tannert@tu-dortmund.de>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
rand_pcg = "0.2.0"
rand_distr = "0.2.2"
uint = { git = "https://github.com/Tockra/uint.git" }
num = "0.2.0"